#NOTE
# Do not use tabs in _config file



# where things are (default)
source:      . # directory where jekyll will read files
destination: ./_site # directory where jekyll will write files
plugins_dir: _plugins
layouts_dir: _layouts
data_dir:    _data
collections:
 posts:
  output:    true

# Handling Reading (default)
safe:         false # true will disable custom plugins and ignore symbolic links
include:      [".htaccess"] # force inclusion of dir or files in the conversion (dotfiles are excluded by default)
exclude:      ["Gemfile", "Gemfile.lock", "node_modules"] # exclude directories or files from conversion (relative to site's source dir)
keep_files:   [".git", ".svn"] # when cleaning the site destination, keel the selected files
encoding:     "utf-8" # set encodings of files
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false # cause a build to fail if there is a YAML syntax error in a page's front matter

# Filtering Content (default)
show_drafts: null # process and render draft posts
limit_posts: 0
future:      false # publish posts with a future date
unpublished: false # render posts that were marked as unpublished

# Plugins (default)
whitelist:   []
plugins:     []

# Conversion (default)
markdown:    kramdown
highlighter: rouge
lsi:         false # produce an index for related posts
excerpt_separator: "\n\n"
incremental: false # experimental incremental build option

# markdown processors
rdiscount:
 extensions: []

redcarpet:
 extensions: []

kramdown:
  math_engine: mathjax

# Serving
detach:  false # detach the server from the terminal
port:    4000
host:    0.0.0.0
baseurl: "" # does not include hostname # the subpath of your site, e.g. /blog/
show_dir_listing: false

# Backwards-compatibility (default)
relative_permalinks: false

# Outputting (default)
permalink:     date
paginate_path: /page:num
timezone:      null # set time zone for site generation. Default is local OS time zone.

quiet:    false
verbose:  false
defaults: []


#--------------------------------------
# Site settings
#--------------------------------------

title: Custom Website Title
description: > # this means to ignore newlines until next tag "baseurl:"
  This is Aakansh Gupta's website. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: machine learning, artificial intelligence, big data, data science, mathematics, statistics, learning, modelling
production_url: 
url: "http://aakansh.gupta.com" # the base hostname & protocol for your site

#author:
author: Aakansh Gupta
twitter: aakansh9
github:  aakansh9
email: aakansh9+contact@gmail.com
linkedin: aakanshgupta



